### ISSUE TITLE
vibration support

### ISSUE THREAD

**Issue by erjoalgo** [mupen64plus/mupen64plus-input-sdl#130]
I bought this Nintendo 64 wireless USB controller that claims to support vibration, but I've been unable to setup vibration or rumble support.

I have tried changing the value of `Rumblepak switch = key(${KEY})` with `$KEY` ranging from 0 to 400, but for every such value I get this error upon startup:

```
Input Warning: Couldn't open rumble support for joystick #1
```

How can I enable vibration/rumble support for this controller? Or how would I go about attempting to discover or test vibration support?

I've tried `jstest-gtk` but I do not see any buttons or keys related to vibration/rubmle.

Below is the config I am using for this controller, which works except for the rumble switch setting.

```
; SAFFUN Wireless USB PC Game pad Joystick
[SWITCH CO.,LT D. Usb Controller]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 0,0
AnalogPeak = 32766,32766
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(6)
B Button = button(1)
A Button = button(2)
C Button R = button(10)
C Button L = button(0)
C Button D = button(3)
C Button U = button(11)
R Trig = button(5)
L Trig = button(4)
; Mempak switch = key(??)
Rumblepak switch = key(4)
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)
```

**Comment by richard42** [comment]
This error message indicates that your SDL library doesn't support haptic feedback with this joystick.

**Comment by erjoalgo** [comment]
How do I fix it?

**Comment by richard42** [comment]
That is a good question, and unfortunately I don't really have an answer for that. I don't know how SDL deals with these things internally. I see that they changed their API and our code uses the newer API when built against SDL 2.0.18 or later. So one relatively easy thing you could do is get/build a newer SDL library and try it with that. Maybe it will work, though I think the chances are not that great.  The only way that I know you could for sure make it would would be:

1. Get the latest SDL source code from github or wherever they keep it
2. Get it building on your target machine
3. Dig through their code to figure out how they pass these haptic API commands on to the controller in Linux on your target machine.
4. Test and debug with your controller to understand what's different about it and why it doesn't work when we give it commands like this to start and stop the rumble (from mupen64plus-input-sdl/src/plugin.c):
```
  if (*Data) {
      SDL_HapticRumblePlay(controller[Control].event_joystick, 1, SDL_HAPTIC_INFINITY);
  } else {
      SDL_HapticRumbleStop(controller[Control].event_joystick);
  }
```
5. Fix the SDL library as necessary so that it properly activates your controller, and send the changes via pull request or similar to the SDL team.

Sorry I don't have a simpler solution for you.

**Comment by erjoalgo** [comment]
Thank you for the pointers, I will try it out when I have some time.
